/** Side-effect barrel: each widget module registers its component. */
import './bookmarks';
import './calendar';
import './clock';
import './custom-api';
import './hacker-news';
import './iframe';
import './lobsters';
import './markets';
import './monitor';
import './reddit';
import './releases';
import './repository';
import './rss';
import './search';
import './todo';
import './twitch';
import './videos';
import './weather';
